### PR TITLE
Update wgpu to 0.7 and egui to 0.8.0

### PR DESCRIPTION
**Pull request by DasEtwas**
This update also..
* reexports the newly added `epi` crate from egui.
* fixes a bug where some layouts trying to render scissors of area 0 or out of bounds would crash in wgpu.

### CODE REVIEW

**Comment by hasenbanck** [comment]
We have some merge conflicts.

**Comment by DasEtwas** [comment]
Working on it

**Comment by DasEtwas** [comment]
Alright, ready for review.

**Comment by hasenbanck** [comment]
LGTM. I will release a new version on crates.io. Could you maybe update the example?

**Pull request merged**
