### PR TITLE
Delete Cargo.lock

### PR DESCRIPTION
**Pull request by DasEtwas**
As per this guide https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html, `Cargo.lock` should only be tracked for end-products. Including the lock file in this library may cause inefficient dependency resolution (doubling, version mismatches, etc.).

### CODE REVIEW

**Comment by hasenbanck** [comment]
Please also add the lock file in the .gitignore then.

**Comment by DasEtwas** [comment]
Mondays.

**Comment by hasenbanck** [comment]
LGTM. Btw: The Cargo.lock is never pulished to crates.io and this is only affecting local development.

**Comment by hasenbanck** [comment]
Uhm .... Github ... yes ... the file is deleted, why are you now showing me a merge conflict? Could you rebase?

**Comment by DasEtwas** [comment]
> LGTM. Btw: The Cargo.lock is never pulished to crates.io and this is only affecting local development.

Good to know :)

**Pull request merged**
