### PR TITLE
Update to wgpu 0.10

### PR DESCRIPTION
**Pull request by niklaskorz**
Updates wgpu dependency to 0.10 and fixes breaking changes in the code.

### CODE REVIEW

**Comment by hasenbanck** [comment]
The PR was still in draft status. Do you want to add something? Or should I merge it?

**Comment by niklaskorz** [comment]
I'm experiencing some issues with the rendered frames, they are way too dark (see https://github.com/niklaskorz/linon/). Not entirely sure if it's an issue in my project or in the egui wgpu backend. Still investigating, so I put it in draft mode for now.

**Comment by hasenbanck** [comment]
I'm not using egui anymore, so I can't assist you with debugging. I'm just maintaining the PRs and the release process.

**Comment by niklaskorz** [comment]
So it's looks like an issue in the egui wgpu backend code, might be related to the sRGB conversion...

wgpu 0.10:

egui with wgpu 0.10

wgpu 0.9:

egui with wgpu 0.9

**Comment by hasenbanck** [comment]
What does it do when you change:

```rust
    let mut sc_desc = wgpu::SwapChainDescriptor {
        usage: wgpu::TextureUsage::RENDER_ATTACHMENT,
        format: OUTPUT_FORMAT,
        width: size.width as u32,
        height: size.height as u32,
        present_mode: wgpu::PresentMode::Mailbox,
    };
````


```rust
    let mut sc_desc = wgpu::SwapChainDescriptor {
        usage: wgpu::TextureUsage::RENDER_ATTACHMENT,
        format: adapter.get_swap_chain_preferred_format(&surface).unwrap(),
        width: size.width as u32,
        height: size.height as u32,
        present_mode: wgpu::PresentMode::Mailbox,
    };
````

In the example?

**Comment by niklaskorz** [comment]
The outcome is the same, unfortunately.

**Comment by niklaskorz** [comment]
Disabling the sRGB conversion in the shader doesn't look right either:

grafik

**Comment by Gordon-F** [comment]
@niklaskorz `select()` order of true/false was swapped in `naga` 0.6. This should fix "dark" output.

https://github.com/hasenbanck/egui_wgpu_backend/blob/master/src/shader/egui.wgsl#L18

**Comment by niklaskorz** [comment]
That's it! Thanks a lot @Gordon-F 

Ready to merge :) @hasenbanck

**Comment by hasenbanck** [comment]
LGTM

**Pull request merged**
